#!/usr/bin/env bash

if [ -f ".env" ]; then
  set -a
  . ./.env
  set +a
fi

export PLANNER_MODEL="${PLANNER_MODEL:-Qwen/Qwen2.5-VL-3B-Instruct}"
export JUDGE_MODEL="${JUDGE_MODEL:-Qwen/Qwen2.5-VL-3B-Instruct}"
export REPORT_MODEL="${REPORT_MODEL:-Qwen/Qwen2.5-VL-7B-Instruct}"
export REFLECTOR_MODEL="${REFLECTOR_MODEL:-Qwen/Qwen2.5-VL-7B-Instruct}"

export LOCAL_SEMANTIC_ENABLED="${LOCAL_SEMANTIC_ENABLED:-true}"
export SEMANTIC_LOCAL_FAST_MODEL="${SEMANTIC_LOCAL_FAST_MODEL:-/home/ronin/THEMIS/models/Qwen2.5-VL-3B-Instruct}"
export SEMANTIC_LOCAL_STRONGER_MODEL="${SEMANTIC_LOCAL_STRONGER_MODEL:-/home/ronin/THEMIS/models/Qwen2.5-VL-7B-Instruct}"
export LOCAL_SEMANTIC_MODEL="${LOCAL_SEMANTIC_MODEL:-$SEMANTIC_LOCAL_FAST_MODEL}"
export LOCAL_SEMANTIC_DEVICE="${LOCAL_SEMANTIC_DEVICE:-cuda}"
export LOCAL_SEMANTIC_QUANTIZATION="${LOCAL_SEMANTIC_QUANTIZATION:-4bit}"
export LOCAL_SEMANTIC_MAX_NEW_TOKENS="${LOCAL_SEMANTIC_MAX_NEW_TOKENS:-220}"

export LOCAL_ARTIFACT_ENABLED="${LOCAL_ARTIFACT_ENABLED:-true}"
export LOCAL_ARTIFACT_METRICS="${LOCAL_ARTIFACT_METRICS:-maniqa,musiq}"
export LOCAL_ARTIFACT_DEVICE="${LOCAL_ARTIFACT_DEVICE:-cuda}"

export LOCAL_IMAGE_MAX_SIDE="${LOCAL_IMAGE_MAX_SIDE:-1024}"
export SEMANTIC_ESCALATION_THRESHOLD="${SEMANTIC_ESCALATION_THRESHOLD:-0.72}"
export ARTIFACT_CONFIDENCE_THRESHOLD="${ARTIFACT_CONFIDENCE_THRESHOLD:-0.55}"

export MAX_PLAN_REVISIONS="${MAX_PLAN_REVISIONS:-2}"
export MAX_REFLECTION_REVISIONS="${MAX_REFLECTION_REVISIONS:-1}"
