import os
import sys
import re
import json
import base64
import time
from pathlib import Path
from datetime import datetime
from openai import OpenAI

if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

PROJECT_ROOT = Path(__file__).resolve().parent.parent

TAXONOMY_DIR = PROJECT_ROOT / "taxonomy_info"
EXPERTS_REGISTRY_JSON = PROJECT_ROOT / "expert_registry.json"

DASHSCOPE_API_KEY = os.environ.get("DASHSCOPE_API_KEY", "")
DASHSCOPE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
JUDGE_MODEL = "qwen3.6-plus"


def encode_image(image_path: str) -> str:
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def load_experts_registry(file_path: str = str(EXPERTS_REGISTRY_JSON)) -> str:
    with open(file_path, "r", encoding="utf-8") as f:
        return json.dumps(json.load(f), indent=2)


def get_taxonomy_info(class_id: int) -> dict | None:
    batch_num = class_id // 10
    batch_file = TAXONOMY_DIR / f"taxonomy_enriched_Batch_{batch_num}.json"
    if not batch_file.exists():
        return None
    with open(batch_file, "r", encoding="utf-8") as f:
        items = json.load(f)
    for item in items:
        if item.get("class_id") == class_id:
            return item
    return None


def clean_json_response(raw_text: str) -> str:
    text = raw_text.strip()
    if text.startswith("```json"):
        text = text[len("```json"):]
    elif text.startswith("```"):
        text = text[len("```"):]
    if text.endswith("```"):
        text = text[:-len("```")]
    return text.strip()


def parse_json_safely(raw_text: str) -> dict | None:
    cleaned = clean_json_response(raw_text)
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", cleaned)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                return None
        return None


def build_judge_prompt(
    plan: dict,
    class_label: str,
    taxonomy_info: dict | None,
    experts_registry_str: str,
) -> str:
    taxonomy_desc = "No specific taxonomy prior knowledge found for this class."
    taxonomy_class_name = class_label
    if taxonomy_info:
        taxonomy_class_name = taxonomy_info.get("class_name", class_label)
        taxonomy_desc = taxonomy_info.get("enriched_description", taxonomy_desc)

    expert_applicability_notes = _build_expert_applicability_notes(experts_registry_str)

    return f"""You are the **Chief Auditor of Evaluation Strategies (Judge)**. Your responsibility is to rigorously review the "Evaluation Plan" generated by the Router Agent for an AI-generated image auditing system.

**[Context]**
- **Target Class:** {class_label}
- **Taxonomy Class Name:** {taxonomy_class_name}
- **Taxonomy Prior Knowledge (Ground Truth):** {taxonomy_desc}
- **Expert Registry (Available Tools):** {experts_registry_str}

**[CRITICAL: Image-Centric Review]**
The evaluation plan should cover ALL visible subjects in the image, not just the class label subject. For example, if the image shows a person holding a fish (class = tench), the plan should also audit the person for artifacts (melting limbs, missing fingers, face distortion). Each expert in the plan has a `target_subject` field indicating which subject it applies to. You MUST verify that each expert's capabilities are compatible with its `target_subject`.

**[Expert Applicability Constraints (MUST READ)]**
{expert_applicability_notes}

**[The Plan to Audit]**
{json.dumps(plan, indent=2, ensure_ascii=False)}

**[Evaluation Dimensions]**
1. **Expert Necessity & Applicability:** For each selected expert, is it truly necessary AND is its `target_subject` compatible with its capabilities? Check the Expert Applicability Constraints above. An expert must NOT be applied to a `target_subject` whose morphology is incompatible. For example, `animal_pose_auditor` with `target_subject: "the fish"` is a category error, but `animal_pose_auditor` with `target_subject: "the person holding the fish"` is valid.
2. **Missing Experts:** Are there critical experts missing for ANY visible subject in the image? You MUST base this judgment on the `applicable_scenes` and `best_for` fields of each expert, NOT on blanket rules like "all animals need pose estimation." Consider all subjects visible in the image: the class subject, any people, and any other objects that could exhibit AI-generation artifacts.
3. **Weight Rationality:** Do the weight allocations reflect structural criticality? The class subject's experts should generally have higher weights; auxiliary subjects' experts can have lower weights.
4. **Focus Areas Completeness:** Do the focus areas cover the most critical diagnostic features for ALL visible subjects, as mentioned in the Taxonomy Prior Knowledge?
5. **Custom Prompts Quality:** Are the custom prompts for the Reflector specific and actionable enough?

**[Critical Rules]**
- Do NOT reject a plan for missing an expert if that expert's capabilities are incompatible with ALL subjects in the image.
- Do NOT suggest adding an expert whose `best_for` description does not match any visible subject's morphology.
- When evaluating "missing experts," always cross-reference the expert's `applicable_scenes` and `best_for` with the actual subjects visible in the image.
- If an expert is selected with a `target_subject` that is incompatible with the expert's capabilities, flag this as an error.

**[Output Requirement]**
Return a pure JSON object (no Markdown wrapping) with this exact schema:
{{
  "is_approved": true,
  "reasons_for_rejection": "",
  "suggestions": []
}}

If the plan is reasonable and passes all evaluation dimensions, set `is_approved` to `true`, leave `reasons_for_rejection` as an empty string, and `suggestions` as an empty array.

If the plan has issues, set `is_approved` to `false`, provide detailed `reasons_for_rejection` explaining what is wrong, and list specific `suggestions` for how to fix the plan.

Output ONLY the JSON object, no additional text."""


def _build_expert_applicability_notes(experts_registry_str: str) -> str:
    try:
        registry = json.loads(experts_registry_str)
    except (json.JSONDecodeError, TypeError):
        return "Could not parse expert registry. Use your best judgment."

    notes = []
    for expert in registry:
        expert_id = expert.get("expert_id", "unknown")
        best_for = expert.get("best_for", "N/A")
        applicable_scenes = expert.get("applicable_scenes", [])
        topology_map = expert.get("topology_map", None)

        note = f"- **{expert_id}**: best_for = \"{best_for}\""
        if applicable_scenes:
            note += f" | applicable_scenes = {json.dumps(applicable_scenes)}"
        if topology_map:
            note += (
                f" | NOTE: This expert uses a fixed topology map: {json.dumps(topology_map)}. "
                f"It is ONLY applicable to `target_subject` values whose body plan matches this topology "
                f"(i.e., subjects with limbs such as humans, dogs, cats). "
                f"It is NOT applicable to limbless subjects (fish, snakes, worms, etc.). "
                f"However, if the image contains a person (e.g., someone holding the animal), "
                f"this expert CAN be applied to that person as the `target_subject`."
            )
        notes.append(note)

    return "\n".join(notes)


def review_plan(
    client: OpenAI,
    image_path: str,
    class_id: int,
    class_label: str,
    plan: dict,
    experts_registry_str: str,
) -> dict | None:
    taxonomy_info = get_taxonomy_info(class_id)
    if taxonomy_info is None:
        print(f"  [WARN] No taxonomy info for class_id={class_id}, proceeding without prior knowledge.")

    base64_image = encode_image(image_path)
    prompt = build_judge_prompt(plan, class_label, taxonomy_info, experts_registry_str)

    try:
        completion = client.chat.completions.create(
            model=JUDGE_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a meta-cognitive Judge Agent. You rigorously analyze evaluation strategies "
                        "for logical rigor, scientific validity, and completeness. You must output JSON only."
                    ),
                },
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{base64_image}"
                            },
                        },
                    ],
                },
            ],
            response_format={"type": "json_object"},
            temperature=0.1,
        )
        raw_content = completion.choices[0].message.content
        result = parse_json_safely(raw_content)
        if result is None:
            print(f"  [ERROR] Judge returned unparseable JSON: {raw_content[:200]}")
            return None
        return result
    except Exception as e:
        print(f"  [ERROR] Judge API call failed: {e}")
        return None
