import os
import sys
import re
import json
import base64
import time
from pathlib import Path
from datetime import datetime
from openai import OpenAI

if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

PROJECT_ROOT = Path(__file__).resolve().parent.parent

TAXONOMY_DIR = PROJECT_ROOT / "taxonomy_info"
EXPERTS_REGISTRY_JSON = PROJECT_ROOT / "expert_registry.json"

DASHSCOPE_API_KEY = os.environ.get("DASHSCOPE_API_KEY", "")
DASHSCOPE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
JUDGE_MODEL = "qwen3.6-plus"


def encode_image(image_path: str) -> str:
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def load_experts_registry(file_path: str = str(EXPERTS_REGISTRY_JSON)) -> str:
    with open(file_path, "r", encoding="utf-8") as f:
        return json.dumps(json.load(f), indent=2)


def get_taxonomy_info(class_id: int) -> dict | None:
    batch_num = class_id // 10
    batch_file = TAXONOMY_DIR / f"taxonomy_enriched_Batch_{batch_num}.json"
    if not batch_file.exists():
        return None
    with open(batch_file, "r", encoding="utf-8") as f:
        items = json.load(f)
    for item in items:
        if item.get("class_id") == class_id:
            return item
    return None


def clean_json_response(raw_text: str) -> str:
    text = raw_text.strip()
    if text.startswith("```json"):
        text = text[len("```json"):]
    elif text.startswith("```"):
        text = text[len("```"):]
    if text.endswith("```"):
        text = text[:-len("```")]
    return text.strip()


def parse_json_safely(raw_text: str) -> dict | None:
    cleaned = clean_json_response(raw_text)
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", cleaned)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                return None
        return None


def build_judge_registry_summary(experts_registry_str: str) -> str:
    try:
        registry = json.loads(experts_registry_str)
    except (json.JSONDecodeError, TypeError):
        return experts_registry_str

    summary = []
    for e in registry:
        entry = {
            "expert_id": e.get("expert_id"),
            "best_for": e.get("best_for"),
            "applicable_scenes": e.get("applicable_scenes"),
        }
        if e.get("topology_map"):
            entry["topology_map"] = e["topology_map"]
            entry["morphology_note"] = "ONLY for limbed subjects. NOT for limbless (fish, snakes)."
        summary.append(entry)

    return json.dumps(summary, indent=2, ensure_ascii=False)


def build_judge_prompt(
    plan: dict,
    class_label: str,
    taxonomy_info: dict | None,
    experts_registry_str: str,
) -> tuple[str, str]:
    taxonomy_desc = "No specific taxonomy prior knowledge found for this class."
    taxonomy_class_name = class_label
    if taxonomy_info:
        taxonomy_class_name = taxonomy_info.get("class_name", class_label)
        taxonomy_desc = taxonomy_info.get("enriched_description", taxonomy_desc)

    registry_summary = build_judge_registry_summary(experts_registry_str)

    prompt = f"""Review the evaluation plan generated by the Router, using the Expert Registry provided in the system context.

**[Context]**
- **Target Class:** {class_label}
- **Taxonomy Class Name:** {taxonomy_class_name}
- **Taxonomy Prior Knowledge:** {taxonomy_desc}

**[Image-Centric Review]**
The plan should cover ALL visible subjects (class subject + auxiliary subjects like people, background objects). Each expert has a `target_subject` field. Verify that each expert's capabilities are compatible with its `target_subject` (check applicable_scenes/best_for/topology_map in Registry).

**[The Plan to Audit]**
{json.dumps(plan, indent=2, ensure_ascii=False)}

**[Evaluation Dimensions]**
1. **Expert Necessity & Applicability:** For each selected expert, is it necessary AND is its `target_subject` compatible with its capabilities? Cross-reference `applicable_scenes`/`best_for`/`topology_map` with the actual subjects. Do NOT reject if an expert is incompatible with ALL subjects — but DO flag if an expert is applied to an incompatible `target_subject`. Do NOT suggest adding an expert whose `best_for` does not match any visible subject's morphology.
2. **Missing Experts:** Are critical experts missing for ANY visible subject? Base this on `applicable_scenes` and `best_for`, NOT blanket rules like "all animals need pose estimation."
3. **Weight Rationality:** Do weights reflect structural criticality? Class subject's experts should generally have higher weights.
4. **Focus Areas Completeness:** Do focus areas cover critical diagnostic features for ALL visible subjects per Taxonomy?
5. **Custom Prompts Quality:** Are custom prompts specific and actionable?

**[Output Requirement]**
Return a pure JSON object (no Markdown wrapping):
{{
  "is_approved": true,
  "reasons_for_rejection": "",
  "suggestions": []
}}

If reasonable, set `is_approved` to `true`. If issues exist, set `is_approved` to `false` with detailed `reasons_for_rejection` and `suggestions`.
Output ONLY the JSON object, no additional text."""

    return prompt, registry_summary


def review_plan(
    client: OpenAI,
    image_path: str,
    class_id: int,
    class_label: str,
    plan: dict,
    experts_registry_str: str,
) -> dict | None:
    taxonomy_info = get_taxonomy_info(class_id)
    if taxonomy_info is None:
        print(f"  [WARN] No taxonomy info for class_id={class_id}, proceeding without prior knowledge.")

    base64_image = encode_image(image_path)
    prompt, registry_summary = build_judge_prompt(plan, class_label, taxonomy_info, experts_registry_str)

    system_msg = (
        "You are a meta-cognitive Judge Agent. You rigorously analyze evaluation strategies "
        "for logical rigor, scientific validity, and completeness. You must output JSON only."
    )
    system_content_text = f"{system_msg}\n\n**[Expert Registry]**\n{registry_summary}"
    system_message = {
        "role": "system",
        "content": [
            {
                "type": "text",
                "text": system_content_text,
                "cache_control": {"type": "ephemeral"},
            }
        ],
    }

    try:
        start_time = time.time()
        completion = client.chat.completions.create(
            model=JUDGE_MODEL,
            messages=[
                system_message,
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{base64_image}"
                            },
                        },
                    ],
                },
            ],
            response_format={"type": "json_object"},
            temperature=0.1,
        )
        cost_time = time.time() - start_time
        raw_content = completion.choices[0].message.content
        result = parse_json_safely(raw_content)
        if result is None:
            print(f"  [ERROR] Judge returned unparseable JSON: {raw_content[:200]}")
            return None

        result["judge_cost_seconds"] = round(cost_time, 2)

        usage = getattr(completion, "usage", None)
        if usage:
            details = getattr(usage, "prompt_tokens_details", None)
            cached = getattr(details, "cached_tokens", 0) if details else 0
            created = getattr(details, "cache_creation_input_tokens", 0) if details else 0
            if cached or created:
                print(f"  [CACHE] Judge: hit={cached} tokens, created={created} tokens")

        return result
    except Exception as e:
        print(f"  [ERROR] Judge API call failed: {e}")
        return None
