import os
import sys
import re
import json
import base64
import time
import argparse
from pathlib import Path
from datetime import datetime
from openai import OpenAI

if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

PROJECT_ROOT = Path(__file__).resolve().parent.parent

IMAGE_DIR = PROJECT_ROOT / "test_images"
CLASS_IDS_TXT = IMAGE_DIR / "class_ids.txt"
TAXONOMY_DIR = PROJECT_ROOT / "taxonomy_info"
EXPERTS_REGISTRY_JSON = PROJECT_ROOT / "expert_registry.json"
IMAGENET_CLASSES_JSON = PROJECT_ROOT / "imagenet_classes.json"
PLAN_DIR = Path(__file__).resolve().parent / "output" / "plans"
OUTPUT_DIR = Path(__file__).resolve().parent / "output" / "approved_plans"

DASHSCOPE_API_KEY = os.environ.get("DASHSCOPE_API_KEY", "")
DASHSCOPE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
JUDGE_MODEL = "qwen3.6-plus"
ROUTER_MODEL = "qwen3.6-plus"


def encode_image(image_path: str) -> str:
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def parse_class_ids(txt_path: str) -> dict[str, int]:
    img_to_class = {}
    if not os.path.exists(txt_path):
        print(f"[WARN] class_ids.txt not found: {txt_path}")
        return img_to_class
    with open(txt_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = re.split(r"\s+", line)
            if len(parts) >= 2:
                try:
                    img_to_class[parts[0]] = int(parts[1])
                except ValueError:
                    continue
    return img_to_class


def load_imagenet_classes(json_path: str) -> dict[int, str]:
    class_map = {}
    if not os.path.exists(json_path):
        print(f"[WARN] imagenet_classes.json not found: {json_path}")
        return class_map
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    for k, v in data.items():
        try:
            class_map[int(k)] = v
        except (ValueError, TypeError):
            continue
    return class_map


def load_experts_registry(file_path: str) -> str:
    with open(file_path, "r", encoding="utf-8") as f:
        return json.dumps(json.load(f), indent=2)


def get_taxonomy_info(class_id: int) -> dict | None:
    batch_num = class_id // 10
    batch_file = TAXONOMY_DIR / f"taxonomy_enriched_Batch_{batch_num}.json"
    if not batch_file.exists():
        return None
    with open(batch_file, "r", encoding="utf-8") as f:
        items = json.load(f)
    for item in items:
        if item.get("class_id") == class_id:
            return item
    return None


def clean_json_response(raw_text: str) -> str:
    text = raw_text.strip()
    if text.startswith("```json"):
        text = text[len("```json"):]
    elif text.startswith("```"):
        text = text[len("```"):]
    if text.endswith("```"):
        text = text[:-len("```")]
    text = text.strip()
    return text


def parse_json_safely(raw_text: str) -> dict | None:
    cleaned = clean_json_response(raw_text)
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", cleaned)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                return None
        return None


def build_judge_prompt(
    plan: dict,
    class_label: str,
    taxonomy_info: dict | None,
    experts_registry_str: str,
) -> str:
    taxonomy_desc = "No specific taxonomy prior knowledge found for this class."
    taxonomy_class_name = class_label
    if taxonomy_info:
        taxonomy_class_name = taxonomy_info.get("class_name", class_label)
        taxonomy_desc = taxonomy_info.get("enriched_description", taxonomy_desc)

    return f"""You are the **Chief Auditor of Evaluation Strategies (Judge)**. Your responsibility is to rigorously review the "Evaluation Plan" generated by the Router Agent for an AI-generated image auditing system.

**[Context]**
- **Target Class:** {class_label}
- **Taxonomy Class Name:** {taxonomy_class_name}
- **Taxonomy Prior Knowledge (Ground Truth):** {taxonomy_desc}
- **Expert Registry (Available Tools):** {experts_registry_str}

**[The Plan to Audit]**
{json.dumps(plan, indent=2, ensure_ascii=False)}

**[Evaluation Dimensions]**
1. **Expert Necessity:** For this class, is each selected expert truly necessary? Are there redundant or irrelevant experts?
2. **Missing Experts:** Are there critical experts missing? For example:
   - Animal classes should typically include `animal_pose_auditor` for anatomical integrity checks.
   - Classes requiring spatial grounding should include `geometric_depth_auditor`.
   - Classes with distinct body parts or components should include `open_vocabulary_detector`.
3. **Weight Rationality:** Do the weight allocations reflect structural criticality? For organisms, anatomy/structure experts should have higher weights; for rigid objects, geometric experts should dominate.
4. **Focus Areas Completeness:** Do the focus areas cover the most critical diagnostic features mentioned in the Taxonomy Prior Knowledge?
5. **Custom Prompts Quality:** Are the custom prompts for the Reflector specific and actionable enough?

**[Output Requirement]**
Return a pure JSON object (no Markdown wrapping) with this exact schema:
{{
  "is_approved": true,
  "reasons_for_rejection": "",
  "suggestions": []
}}

If the plan is reasonable and passes all evaluation dimensions, set `is_approved` to `true`, leave `reasons_for_rejection` as an empty string, and `suggestions` as an empty array.

If the plan has issues, set `is_approved` to `false`, provide detailed `reasons_for_rejection` explaining what is wrong, and list specific `suggestions` for how to fix the plan.

Output ONLY the JSON object, no additional text."""


def build_router_revision_prompt(
    class_label: str,
    taxonomy_info: dict | None,
    experts_registry_str: str,
    original_plan: dict,
    feedback_history: list[dict],
) -> str:
    taxonomy_desc = "No specific taxonomy prior knowledge found for this class."
    taxonomy_class_name = class_label
    if taxonomy_info:
        taxonomy_class_name = taxonomy_info.get("class_name", class_label)
        taxonomy_desc = taxonomy_info.get("enriched_description", taxonomy_desc)

    feedback_text = ""
    for i, fb in enumerate(feedback_history, 1):
        feedback_text += f"\n--- Feedback Round {i} ---\n"
        feedback_text += f"Reasons for Rejection: {fb.get('reasons_for_rejection', 'N/A')}\n"
        feedback_text += f"Suggestions: {json.dumps(fb.get('suggestions', []), ensure_ascii=False)}\n"

    return f"""You are the Lead Strategic Planner (Router) for an advanced AI image evaluation system.
Your previous plan was REJECTED by the Judge. You must revise it based on the feedback below.

**[Input Data]**
- **Class Label:** {class_label}
- **Taxonomy Class Name:** {taxonomy_class_name}
- **Taxonomy Prior Knowledge (Ground Truth):** {taxonomy_desc}
- **Expert Registry (Available Tools):** {experts_registry_str}

**[Your Previous Plan (REJECTED)]**
{json.dumps(original_plan, indent=2, ensure_ascii=False)}

**[Judge Feedback History]**
{feedback_text}

**[Strategic Instruction]**
1. Carefully read the Judge's feedback and understand what was wrong with your previous plan.
2. Revise the plan to address ALL issues raised by the Judge.
3. **Identify Category Archetype:** Determine if the class "{class_label}" is an **Organism** (animal/plant), a **Rigid Object** (architecture/tool/vehicle), or a **Natural Scene** (landscape/texture).
4. **Feature Mapping:** Based on the Taxonomy Prior Knowledge, extract 2-10 "Non-negotiable" diagnostic features that must be verified in the image.
5. **Visual Risk Assessment:** Scrutinize the image for category-specific flaws:
   - *Organisms:* Look for "Melting" limbs, missing parts, or anatomical hallucinations.
   - *Rigid Objects:* Look for warped lines, perspective distortion, or "fusing" into the background.
   - *Scenes:* Look for repetitive patterns (mode collapse) or illogical spatial bleeding.
6. **Expert Selection:** Map the identified risks to specific `expert_name` values from the Registry. You MUST use the exact `expert_id` values from the Expert Registry as the `expert_name` field. Available expert_ids: animal_pose_auditor, geometric_depth_auditor, topology_boundary_auditor, open_vocabulary_detector, fine_grained_classifier, perceptual_quality_auditor, image_text_auditor.
7. **Weight Allocation:** Assign weights based on "Structural Criticality" — anatomy/structure experts should receive higher weights for organisms, geometric experts for rigid objects, etc. All weights for selected experts must sum to 1.0.

**[Output Requirements]**
Return a pure JSON object (no Markdown wrapping) with this exact schema:
{{
  "image_class": "The ImageNet class label string",
  "selected_experts": [
    {{
      "expert_name": "string (must exactly match an expert_id from the Expert Registry)",
      "reason": "Why this expert is selected for this specific class and image",
      "weight": 0.0
    }}
  ],
  "focus_areas": ["string (e.g., feet, facial_details, background, limb_integrity, textural_coherence)"],
  "custom_prompts_for_reflector": "string (special audit hints for the Reflector in later steps)"
}}

**[Constraints]**
- You MUST include "fine_grained_classifier" as one of the selected experts for identity verification.
- You MUST include "open_vocabulary_detector" if the class requires locating specific body parts or components.
- All weights must be positive and sum to 1.0.
- Select 3-5 experts appropriate for the category.
- Output ONLY the JSON object, no additional text."""


def call_judge(
    client: OpenAI,
    base64_image: str,
    prompt: str,
) -> dict | None:
    try:
        completion = client.chat.completions.create(
            model=JUDGE_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a meta-cognitive Judge Agent. You rigorously analyze evaluation strategies "
                        "for logical rigor, scientific validity, and completeness. You must output JSON only."
                    ),
                },
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{base64_image}"
                            },
                        },
                    ],
                },
            ],
            response_format={"type": "json_object"},
            temperature=0.1,
        )
        raw_content = completion.choices[0].message.content
        result = parse_json_safely(raw_content)
        if result is None:
            print(f"  [ERROR] Judge returned unparseable JSON: {raw_content[:200]}")
        return result
    except Exception as e:
        print(f"  [ERROR] Judge API call failed: {e}")
        return None


def call_router_revision(
    client: OpenAI,
    base64_image: str,
    prompt: str,
) -> dict | None:
    try:
        completion = client.chat.completions.create(
            model=ROUTER_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a highly logical Router Agent for image auditing. "
                        "Your previous plan was rejected and you must revise it based on Judge feedback. "
                        "You must prioritize the provided Taxonomy Knowledge as the source of truth. "
                        "Output JSON only."
                    ),
                },
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{base64_image}"
                            },
                        },
                    ],
                },
            ],
            response_format={"type": "json_object"},
            temperature=0.1,
        )
        raw_content = completion.choices[0].message.content
        result = parse_json_safely(raw_content)
        if result is None:
            print(f"  [ERROR] Router revision returned unparseable JSON: {raw_content[:200]}")
        return result
    except Exception as e:
        print(f"  [ERROR] Router revision API call failed: {e}")
        return None


def validate_plan(plan: dict) -> bool:
    if "image_class" not in plan:
        print("  [WARN] Plan missing 'image_class'")
        return False
    if "selected_experts" not in plan or not isinstance(plan["selected_experts"], list):
        print("  [WARN] Plan missing or invalid 'selected_experts'")
        return False
    if "focus_areas" not in plan or not isinstance(plan["focus_areas"], list):
        print("  [WARN] Plan missing or invalid 'focus_areas'")
        return False
    if "custom_prompts_for_reflector" not in plan:
        print("  [WARN] Plan missing 'custom_prompts_for_reflector'")
        return False

    valid_expert_ids = {
        "animal_pose_auditor",
        "geometric_depth_auditor",
        "topology_boundary_auditor",
        "open_vocabulary_detector",
        "fine_grained_classifier",
        "perceptual_quality_auditor",
        "image_text_auditor",
    }
    total_weight = 0.0
    for expert in plan["selected_experts"]:
        if "expert_name" not in expert:
            print(f"  [WARN] Expert entry missing 'expert_name': {expert}")
            return False
        if expert["expert_name"] not in valid_expert_ids:
            print(
                f"  [WARN] Invalid expert_name '{expert['expert_name']}', "
                f"must be one of: {valid_expert_ids}"
            )
            return False
        if "weight" not in expert:
            print(f"  [WARN] Expert '{expert['expert_name']}' missing 'weight'")
            return False
        total_weight += expert["weight"]

    if abs(total_weight - 1.0) > 0.05:
        print(
            f"  [WARN] Expert weights sum to {total_weight:.2f}, expected ~1.0"
        )
    return True


def run_stage2_review_loop(
    client: OpenAI,
    image_path: str,
    class_id: int,
    class_label: str,
    initial_plan: dict,
    taxonomy_info: dict | None,
    experts_registry_str: str,
    max_iterations: int = 3,
) -> dict:
    base64_image = encode_image(image_path)
    current_plan = initial_plan
    feedback_history: list[dict] = []
    iteration_log: list[str] = []

    for iteration in range(1, max_iterations + 1):
        print(f"\n{'='*60}")
        print(f"  Iteration {iteration}/{max_iterations}")
        print(f"{'='*60}")

        judge_prompt = build_judge_prompt(
            current_plan, class_label, taxonomy_info, experts_registry_str
        )

        print(f"  [Judge] Reviewing plan for class '{class_label}'...")
        start_time = time.time()
        judge_result = call_judge(client, base64_image, judge_prompt)
        judge_cost = time.time() - start_time

        if judge_result is None:
            print(f"  [Judge] Failed to get valid response (cost: {judge_cost:.2f}s)")
            print(f"  Iteration {iteration}: Judge Error -> Using current plan")
            iteration_log.append(f"Iteration {iteration}: Judge Error")
            break

        is_approved = judge_result.get("is_approved", False)
        reasons = judge_result.get("reasons_for_rejection", "")
        suggestions = judge_result.get("suggestions", [])

        print(f"  [Judge] Cost: {judge_cost:.2f}s")
        print(f"  [Judge] Verdict: {'Approved' if is_approved else 'Rejected'}")
        if not is_approved:
            print(f"  [Judge] Reasons: {reasons}")
            print(f"  [Judge] Suggestions: {json.dumps(suggestions, ensure_ascii=False)}")

        if is_approved:
            print(f"\n  Iteration {iteration}: Approved!")
            iteration_log.append(f"Iteration {iteration}: Approved!")
            current_plan["metadata"]["judge_approved"] = True
            current_plan["metadata"]["judge_iterations"] = iteration
            current_plan["metadata"]["judge_cost_seconds"] = round(judge_cost, 2)
            break
        else:
            print(f"  Iteration {iteration}: Rejected")
            iteration_log.append(f"Iteration {iteration}: Rejected")

            if iteration == max_iterations:
                print(f"\n  [WARN] Max iterations ({max_iterations}) reached. Forcing approval of latest plan.")
                iteration_log.append(
                    f"Iteration {iteration}: Max iterations reached - forced approval"
                )
                current_plan["metadata"]["judge_approved"] = False
                current_plan["metadata"]["judge_forced"] = True
                current_plan["metadata"]["judge_iterations"] = iteration
                current_plan["metadata"]["judge_cost_seconds"] = round(judge_cost, 2)
                break

            feedback_history.append({
                "reasons_for_rejection": reasons,
                "suggestions": suggestions,
            })

            revision_prompt = build_router_revision_prompt(
                class_label, taxonomy_info, experts_registry_str,
                current_plan, feedback_history,
            )

            print(f"  [Router] Revising plan based on Judge feedback...")
            start_time = time.time()
            revised_plan = call_router_revision(client, base64_image, revision_prompt)
            router_cost = time.time() - start_time

            if revised_plan is None:
                print(f"  [Router] Revision failed (cost: {router_cost:.2f}s). Keeping previous plan.")
                iteration_log.append(f"Iteration {iteration}: Router revision failed")
                continue

            is_valid = validate_plan(revised_plan)
            print(f"  [Router] Revision cost: {router_cost:.2f}s | Valid: {is_valid}")

            if "metadata" not in revised_plan:
                revised_plan["metadata"] = {}
            revised_plan["metadata"]["revision_iteration"] = iteration
            revised_plan["metadata"]["plan_valid"] = is_valid
            revised_plan["metadata"]["router_cost_seconds"] = round(router_cost, 2)

            current_plan = revised_plan

    current_plan["metadata"]["iteration_log"] = iteration_log
    return current_plan


def process_single_plan(
    client: OpenAI,
    plan_path: Path,
    image_dir: Path,
    class_id: int,
    class_label: str,
    taxonomy_info: dict | None,
    experts_registry_str: str,
    max_iterations: int,
    output_dir: Path,
) -> dict | None:
    with open(plan_path, "r", encoding="utf-8") as f:
        plan = json.load(f)

    img_filename = plan.get("metadata", {}).get("image_filename", "")
    if not img_filename:
        img_id = plan_path.stem.replace("plan_", "")
        for ext in [".png", ".jpg", ".jpeg"]:
            candidate = image_dir / f"{img_id}{ext}"
            if candidate.exists():
                img_filename = f"{img_id}{ext}"
                break

    image_path = image_dir / img_filename
    if not image_path.exists():
        print(f"[ERROR] Image not found: {image_path}")
        return None

    print(f"\n{'#'*60}")
    print(f"  Processing: {img_filename} | Class: {class_label}")
    print(f"{'#'*60}")

    approved_plan = run_stage2_review_loop(
        client=client,
        image_path=str(image_path),
        class_id=class_id,
        class_label=class_label,
        initial_plan=plan,
        taxonomy_info=taxonomy_info,
        experts_registry_str=experts_registry_str,
        max_iterations=max_iterations,
    )

    img_id = plan_path.stem.replace("plan_", "")
    save_path = output_dir / f"approved_plan_{img_id}.json"
    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(approved_plan, f, indent=4, ensure_ascii=False)

    print(f"\n  [SAVED] Approved plan -> {save_path}")
    for log_entry in approved_plan["metadata"].get("iteration_log", []):
        print(f"  {log_entry}")

    return approved_plan


def main():
    parser = argparse.ArgumentParser(
        description="THEMIS C2I Step 2: Judge-Router Review Loop - Audit and iterate on evaluation plans"
    )
    parser.add_argument(
        "--max-iterations",
        type=int,
        default=3,
        help="Maximum Judge-Router iteration rounds (default: 3)",
    )
    parser.add_argument(
        "--plan-dir",
        type=str,
        default=str(PLAN_DIR),
        help="Directory containing plan JSON files from Step 1",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=str(OUTPUT_DIR),
        help="Output directory for approved plan JSON files",
    )
    parser.add_argument(
        "--image-dir",
        type=str,
        default=str(IMAGE_DIR),
        help="Directory containing test images",
    )
    parser.add_argument(
        "--class-ids",
        type=str,
        default=str(CLASS_IDS_TXT),
        help="Path to class_ids.txt",
    )
    parser.add_argument(
        "--plan-file",
        type=str,
        default="",
        help="Process a single plan file instead of all plans in plan-dir",
    )
    args = parser.parse_args()

    plan_dir = Path(args.plan_dir)
    output_dir = Path(args.output_dir)
    image_dir = Path(args.image_dir)
    class_ids_txt = Path(args.class_ids)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not DASHSCOPE_API_KEY:
        print("[ERROR] DASHSCOPE_API_KEY not set. Please run:")
        print("  export DASHSCOPE_API_KEY=your_api_key_here  (Linux/Mac)")
        print("  set DASHSCOPE_API_KEY=your_api_key_here     (Windows CMD)")
        return

    client = OpenAI(api_key=DASHSCOPE_API_KEY, base_url=DASHSCOPE_BASE_URL)

    img_to_class = parse_class_ids(str(class_ids_txt))
    imagenet_classes = load_imagenet_classes(str(IMAGENET_CLASSES_JSON))
    experts_registry_str = load_experts_registry(str(EXPERTS_REGISTRY_JSON))

    print(f"\n{'='*60}")
    print(f"THEMIS C2I Judge - Step 2: Judge-Router Review Loop")
    print(f"Max iterations:   {args.max_iterations}")
    print(f"Plan directory:   {plan_dir}")
    print(f"Output directory: {output_dir}")
    print(f"{'='*60}")

    if args.plan_file:
        plan_path = Path(args.plan_file)
        if not plan_path.exists():
            print(f"[ERROR] Plan file not found: {plan_path}")
            return

        with open(plan_path, "r", encoding="utf-8") as f:
            plan_data = json.load(f)

        class_id = plan_data.get("metadata", {}).get("class_id", -1)
        class_label = plan_data.get("metadata", {}).get("class_label", "")

        if class_id < 0:
            img_id = plan_path.stem.replace("plan_", "")
            if img_id in img_to_class:
                class_id = img_to_class[img_id]
                class_label = imagenet_classes.get(class_id, f"class_{class_id}")

        taxonomy_info = get_taxonomy_info(class_id)
        if taxonomy_info is None:
            print(f"[WARN] No taxonomy info for class_id={class_id}")

        process_single_plan(
            client, plan_path, image_dir, class_id, class_label,
            taxonomy_info, experts_registry_str, args.max_iterations, output_dir,
        )
    else:
        plan_files = sorted(plan_dir.glob("plan_*.json"))
        if not plan_files:
            print(f"[ERROR] No plan files found in {plan_dir}")
            return

        print(f"Found {len(plan_files)} plan(s) to review\n")

        success_count = 0
        failed_count = 0
        total_start = time.time()

        for plan_path in plan_files:
            with open(plan_path, "r", encoding="utf-8") as f:
                plan_data = json.load(f)

            class_id = plan_data.get("metadata", {}).get("class_id", -1)
            class_label = plan_data.get("metadata", {}).get("class_label", "")

            if class_id < 0:
                img_id = plan_path.stem.replace("plan_", "")
                if img_id in img_to_class:
                    class_id = img_to_class[img_id]
                    class_label = imagenet_classes.get(class_id, f"class_{class_id}")

            taxonomy_info = get_taxonomy_info(class_id)
            if taxonomy_info is None:
                print(f"[WARN] No taxonomy info for class_id={class_id}")

            result = process_single_plan(
                client, plan_path, image_dir, class_id, class_label,
                taxonomy_info, experts_registry_str, args.max_iterations, output_dir,
            )

            if result is not None:
                success_count += 1
            else:
                failed_count += 1

        total_cost = time.time() - total_start

        print(f"\n{'='*60}")
        print(f"Judge Review Summary")
        print(f"{'='*60}")
        print(f"  Total plans:     {len(plan_files)}")
        print(f"  Successful:      {success_count}")
        print(f"  Failed:          {failed_count}")
        print(f"  Total elapsed:   {total_cost:.2f}s")
        print(f"{'='*60}")


if __name__ == "__main__":
    main()
