import os
import sys
import re
import json
import base64
import time
from pathlib import Path
from datetime import datetime
from openai import OpenAI
from common import api_call_with_retry

if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

PROJECT_ROOT = Path(__file__).resolve().parent.parent

TAXONOMY_DIR = PROJECT_ROOT / "taxonomy_info"
EXPERTS_REGISTRY_JSON = PROJECT_ROOT / "expert_registry.json"

DASHSCOPE_API_KEY = os.environ.get("DASHSCOPE_API_KEY", "")
DASHSCOPE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
JUDGE_MODEL = "qwen3.6-plus"


def encode_image(image_path: str) -> str:
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def load_experts_registry(file_path: str = str(EXPERTS_REGISTRY_JSON)) -> str:
    with open(file_path, "r", encoding="utf-8") as f:
        return json.dumps(json.load(f), indent=2)


def get_taxonomy_info(class_id: int) -> dict | None:
    batch_num = class_id // 10
    batch_file = TAXONOMY_DIR / f"taxonomy_enriched_Batch_{batch_num}.json"
    if not batch_file.exists():
        return None
    with open(batch_file, "r", encoding="utf-8") as f:
        items = json.load(f)
    for item in items:
        if item.get("class_id") == class_id:
            return item
    return None


def clean_json_response(raw_text: str) -> str:
    text = raw_text.strip()
    if text.startswith("```json"):
        text = text[len("```json"):]
    elif text.startswith("```"):
        text = text[len("```"):]
    if text.endswith("```"):
        text = text[:-len("```")]
    return text.strip()


def parse_json_safely(raw_text: str) -> dict | None:
    if raw_text is None or raw_text.strip() == "":
        return None
    cleaned = clean_json_response(raw_text)
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", cleaned)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                return None
        return None


def build_judge_registry_summary(experts_registry_str: str) -> str:
    try:
        registry = json.loads(experts_registry_str)
    except (json.JSONDecodeError, TypeError):
        return experts_registry_str

    summary = []
    for e in registry:
        entry = {
            "expert_id": e.get("expert_id"),
            "description": e.get("description"),
            "best_for": e.get("best_for"),
        }
        if e.get("expert_id") == "animal_pose_auditor":
            entry["note"] = "ONLY for limbed subjects. NOT for limbless (fish, snakes)."
        summary.append(entry)

    return json.dumps(summary, indent=2, ensure_ascii=False)


def build_judge_prompt(
    plan: dict,
    class_label: str,
    taxonomy_info: dict | None,
    experts_registry_str: str,
) -> tuple[str, str]:
    taxonomy_desc = "No specific taxonomy prior knowledge found for this class."
    taxonomy_class_name = class_label
    if taxonomy_info:
        taxonomy_class_name = taxonomy_info.get("class_name", class_label)
        taxonomy_desc = taxonomy_info.get("enriched_description", taxonomy_desc)

    registry_summary = build_judge_registry_summary(experts_registry_str)

    prompt = f"""Review the evaluation plan generated by the Router.

**[Context]**
- Target Class: {class_label}
- Taxonomy: {taxonomy_desc}

**[The Plan to Audit]**
{json.dumps(plan, indent=2, ensure_ascii=False)}

**[Review Dimensions]**
1. **Checkpoint Verdicts:** Are is_testable/is_present judgments reasonable? Did the Router avoid evaluating too many checkpoints by marking them untestable?
2. **Artifact Observations:** Are severity ratings consistent? If no artifacts found, does the image suggest missed issues?
3. **Expert Selection:** Is each expert's target_subject compatible with its capabilities? Are critical experts missing?
4. **Weights:** Do weights reflect structural criticality (class subject > auxiliary)?
5. **Focus Areas:** Do focus areas cover critical diagnostic features?
6. **专家验证覆盖度:** 检查 Router 的 expert_verification_plan：
   1. 所有关键 taxonomy checkpoint 是否都有专家覆盖（或合理标注为 unverifiable）？
   2. 所有 is_present=false 的 checkpoint，是否有 fine_grained_classifier 或
      open_vocabulary_detector 提供反证？
   3. 所有 artifact_observations 是否都有 perceptual_quality_auditor 覆盖？
   4. verification_goals 是否与 checkpoint_verdicts 中的描述一一对应？
   5. unverifiable_points 中的点是否确实无法用专家验证？
   如果覆盖不完整，在 suggestions 中指出缺失的验证目标。

**[Output]**
Return JSON only:
{{
  "is_approved": true,
  "reasons_for_rejection": "",
  "suggestions": [{{"type": "missing_verification", "point": "str", "recommended_expert": "str"}}],
  "coverage_assessment": {{
    "checkpoints_covered": 0,
    "checkpoints_total": 0,
    "artifacts_covered": 0,
    "artifacts_total": 0,
    "unverifiable_count": 0
  }}
}}"""

    return prompt, registry_summary


def review_plan(
    client: OpenAI,
    image_path: str,
    class_id: int,
    class_label: str,
    plan: dict,
    experts_registry_str: str,
    api_retry: int = 0,
    temperature: float = 0.0,
) -> dict | None:
    taxonomy_info = get_taxonomy_info(class_id)
    if taxonomy_info is None:
        print(f"  [WARN] No taxonomy info for class_id={class_id}, proceeding without prior knowledge.")

    start_time = time.time()

    base64_image = encode_image(image_path)
    prompt, registry_summary = build_judge_prompt(plan, class_label, taxonomy_info, experts_registry_str)

    system_msg = (
        "You are a meta-cognitive Judge Agent. You rigorously analyze evaluation strategies "
        "for logical rigor, scientific validity, and completeness. You must output JSON only."
    )
    system_content_text = f"{system_msg}\n\n**[Expert Registry]**\n{registry_summary}"
    system_message = {
        "role": "system",
        "content": [
            {
                "type": "text",
                "text": system_content_text,
                "cache_control": {"type": "ephemeral"},
            }
        ],
    }

    try:
        completion = api_call_with_retry(
            client.chat.completions.create,
            model=JUDGE_MODEL,
            messages=[
                system_message,
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{base64_image}"
                            },
                        },
                    ],
                },
            ],
            response_format={"type": "json_object"},
            temperature=temperature,
            max_retries=api_retry,
            label="Judge",
            extra_body={"enable_thinking": False},
        )
        cost_time = time.time() - start_time
        raw_content = completion.choices[0].message.content
        finish_reason = getattr(completion.choices[0], "finish_reason", "unknown")
        usage = getattr(completion, "usage", None)
        if raw_content is None or raw_content.strip() == "":
            reasoning = getattr(completion.choices[0].message, "reasoning_content", None)
            usage_info = f"prompt_tokens={usage.prompt_tokens}, completion_tokens={usage.completion_tokens}" if usage else "no usage info"
            print(f"  [ERROR] Judge returned empty content (content is {'None' if raw_content is None else 'empty string'}, finish_reason={finish_reason}, {usage_info})")
            if reasoning:
                print(f"  [WARN] Judge reasoning_content found ({len(reasoning)} chars), attempting to extract JSON")
                raw_content = reasoning
            else:
                msg = completion.choices[0].message
                print(f"  [DEBUG] Judge full message: content={repr(msg.content)}, role={getattr(msg, 'role', 'N/A')}, function_call={getattr(msg, 'function_call', None)}, tool_calls={getattr(msg, 'tool_calls', None)}, refusal={getattr(msg, 'refusal', None)}")
                return None
        result = parse_json_safely(raw_content)
        if result is None:
            print(f"  [ERROR] Judge returned unparseable JSON: {raw_content[:200]}")
            return None

        result["judge_cost_seconds"] = round(cost_time, 2)

        usage = getattr(completion, "usage", None)
        if usage:
            details = getattr(usage, "prompt_tokens_details", None)
            cached = getattr(details, "cached_tokens", 0) if details else 0
            created = getattr(details, "cache_creation_input_tokens", 0) if details else 0
            if cached or created:
                print(f"  [CACHE] Judge: hit={cached} tokens, created={created} tokens")

        return result
    except Exception as e:
        print(f"  [ERROR] Judge API call failed: {type(e).__name__}: {e}")
        return None
