import os
import json
from openai import OpenAI
from datetime import datetime

# 1. 初始化客户端
client = OpenAI(
    api_key="sk-9165cc69015b4a12ab542fb5edc20612",
    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
)

# --- 配置区 ---
plan_file_path = "evaluation_plans_output/plan_000052.json"
taxonomy_json_path = "taxonomy_enriched.json"
output_judge_dir = "judge_reports_output"
os.makedirs(output_judge_dir, exist_ok=True)
# --------------

# 2. 工具函数：加载数据
def load_json(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        return json.load(f)

# 3. 准备 Judge 专用的 Prompt
def build_judge_prompt(plan_data, taxonomy_info):
    return f"""You are the **Chief Auditor of Evaluation Strategies**. Your responsibility is to review the "Evaluation Plan" generated by a Router Agent.

**[Context]**
- **Target Class:** {plan_data['metadata']['class_label']}
- **Reference Taxonomy:** {taxonomy_info}

**[The Plan to Audit]**
{json.dumps(plan_data, indent=2)}

**[Evaluation Dimensions]**
1. **Categorical Logic:** Is the `category_archetype` correct?
2. **Prior Knowledge Alignment:** Does the `semantic_baseline` capture the 'Golden Standards' from the taxonomy?
3. **Expert Selection & Stage Logic:** Are the experts appropriate and the sequence logical?
4. **Weight Distribution:** Do weights reflect structural criticality (Anatomy > Aesthetics for organisms)?
5. **Conflict Resolution:** Is the strategy decisive and physically grounded?

**[Output Requirement]**
Return JSON ONLY in this schema:
{{
  "plan_quality_grade": "A | B | C | D",
  "strengths": ["string"],
  "weaknesses": ["string"],
  "logical_gaps": "string",
  "weight_optimization_suggestion": "string",
  "final_verdict": "Approved | Needs Revision | Rejected",
  "reasoning": "string"
}}"""

# 4. 执行 Judge 流程
try:
    # 加载计划内容
    plan_data = load_json(plan_file_path)
    class_label = plan_data['metadata']['class_label']
    
    # 获取该类别的原始先验知识（用于 Judge 比对 Planner 有没有偷懒）
    taxonomy_data = load_json(taxonomy_json_path)
    taxonomy_info = next((item['enriched_description'] for item in taxonomy_data 
                          if class_label.lower() in item['class_name'].lower()), "No taxonomy found.")

    print(f"Auditing plan for: {class_label}...")

    # 调用 API
    completion = client.chat.completions.create(
        model="qwen3.6-plus",
        messages=[
            {
                "role": "system", 
                "content": "You are a meta-cognitive Judge. You analyze evaluation strategies for logical rigor and scientific validity. Output JSON only."
            },
            {
                "role": "user", 
                "content": build_judge_prompt(plan_data, taxonomy_info)
            }
        ],
        response_format={"type": "json_object"},
        temperature=0.1
    )

    # 5. 解析并保存审核报告
    judge_report = json.loads(completion.choices[0].message.content)
    
    # 文件命名保持一致性：judge_000052.json
    image_id = os.path.basename(plan_file_path).replace("plan_", "").replace(".json", "")
    save_path = os.path.join(output_judge_dir, f"judge_{image_id}.json")
    
    # 注入元数据
    judge_report["metadata"] = {
        "reviewed_plan": plan_file_path,
        "judged_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(judge_report, f, indent=4, ensure_ascii=False)

    print(f"Judge Report saved to: {save_path}")
    print(f"Final Verdict: {judge_report['final_verdict']}")

except Exception as e:
    print(f"Error during Judging: {e}")