import os
import sys
import re
import json
import base64
import time
from pathlib import Path
from datetime import datetime
from openai import OpenAI

if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
T2I_DIR = Path(__file__).resolve().parent
C2I_DIR = PROJECT_ROOT / "c2i_harness"

# Add c2i_harness at the END of sys.path so it doesn't shadow t2i_harness modules
# (c2i_harness contains common.py and same-named step1/step2 modules).
if str(C2I_DIR) not in sys.path:
    sys.path.append(str(C2I_DIR))
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(T2I_DIR) not in sys.path:
    sys.path.insert(0, str(T2I_DIR))

from common import api_call_with_retry

# common.py may have inserted c2i_harness at position 0 (e.g. due to drive-letter
# casing differences on Windows), which would shadow t2i_harness modules of the
# same name. Re-assert t2i_harness at the front of sys.path.
_t2i_dir_str = str(T2I_DIR)
if _t2i_dir_str in sys.path:
    sys.path.remove(_t2i_dir_str)
sys.path.insert(0, _t2i_dir_str)

TAXONOMY_DIR = PROJECT_ROOT / "taxonomy_info"
EXPERTS_REGISTRY_JSON = PROJECT_ROOT / "expert_registry.json"

DASHSCOPE_API_KEY = os.environ.get("DASHSCOPE_API_KEY", "")
DASHSCOPE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
JUDGE_MODEL = "qwen3.6-plus"


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Utility Functions
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def encode_image(image_path: str) -> str:
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")


def load_experts_registry(file_path: str = str(EXPERTS_REGISTRY_JSON)) -> str:
    with open(file_path, "r", encoding="utf-8") as f:
        return json.dumps(json.load(f), indent=2)


def get_taxonomy_info(class_id: int) -> dict | None:
    batch_num = class_id // 10
    batch_file = TAXONOMY_DIR / f"taxonomy_enriched_Batch_{batch_num}.json"
    if not batch_file.exists():
        return None
    with open(batch_file, "r", encoding="utf-8") as f:
        items = json.load(f)
    for item in items:
        if item.get("class_id") == class_id:
            return item
    return None


def clean_json_response(raw_text: str) -> str:
    text = raw_text.strip()
    if text.startswith("```json"):
        text = text[len("```json"):]
    elif text.startswith("```"):
        text = text[len("```"):]
    if text.endswith("```"):
        text = text[:-len("```")]
    return text.strip()


def parse_json_safely(raw_text: str) -> dict | None:
    if raw_text is None or raw_text.strip() == "":
        return None
    cleaned = clean_json_response(raw_text)
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", cleaned)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                return None
        return None


def build_judge_registry_summary(experts_registry_str: str) -> str:
    try:
        registry = json.loads(experts_registry_str)
    except (json.JSONDecodeError, TypeError):
        return experts_registry_str

    summary = []
    for e in registry:
        entry = {
            "expert_id": e.get("expert_id"),
            "description": e.get("description"),
            "best_for": e.get("best_for"),
        }
        if e.get("expert_id") == "animal_pose_auditor":
            entry["note"] = "ONLY for limbed subjects. NOT for limbless (fish, snakes)."
        summary.append(entry)

    return json.dumps(summary, indent=2, ensure_ascii=False)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Judge Prompt Building (T2I-specific)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def build_judge_prompt(
    plan: dict,
    prompt_text: str,
    atoms: list,
    experts_registry_str: str,
) -> tuple[str, str]:
    registry_summary = build_judge_registry_summary(experts_registry_str)

    atoms_text = "No atoms available."
    if atoms:
        atoms_lines = []
        for atom in atoms:
            idx = atom.get("atom_index", "?")
            question = atom.get("question", "?")
            expected = atom.get("expected", "?")
            atoms_lines.append(
                f"  - Atom {idx}: Q: {question} | Expected: {expected}"
            )
        atoms_text = "\n".join(atoms_lines)

    prompt = f"""Review the evaluation plan generated by the Router (Text-to-Image mode).

**[Context]**
- Prompt: {prompt_text}
- Atoms (QA questions derived from the prompt):
{atoms_text}

**[The Plan to Audit]**
{json.dumps(plan, indent=2, ensure_ascii=False)}

**[Review Dimensions]**
1. **Atom QA Coverage:** Did the Router answer ALL atoms? Are the predicted answers and is_correct judgments reasonable? Are confidence scores calibrated?
2. **Taxonomy Checkpoint Reasonableness:** For each object, are is_testable/is_present judgments reasonable? Did the Router avoid evaluating too many checkpoints by marking them untestable?
3. **Artifact Observations:** Are severity ratings consistent? If no artifacts found, does the image suggest missed issues?
4. **Expert Selection:** Is each expert's target_subject compatible with its capabilities? Are critical experts missing? Are all prompt objects covered?
5. **Weights:** Do weights reflect structural criticality (main objects > auxiliary)?

**[Output]**
Return JSON only:
{{
  "is_approved": true,
  "reasons_for_rejection": "",
  "suggestions": []
}}"""

    return prompt, registry_summary


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Plan Review (T2I-specific)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def review_plan(
    client: OpenAI,
    image_path: str,
    prompt_id: str,
    prompt_text: str,
    atomized_data: dict,
    plan: dict,
    experts_registry_str: str,
    api_retry: int = 0,
    temperature: float = 0.0,
) -> dict | None:
    atoms = atomized_data.get("atoms", [])

    start_time = time.time()

    base64_image = encode_image(image_path)
    prompt, registry_summary = build_judge_prompt(plan, prompt_text, atoms, experts_registry_str)

    system_msg = (
        "You are a meta-cognitive Judge Agent for Text-to-Image evaluation. "
        "You rigorously analyze evaluation strategies for logical rigor, scientific validity, "
        "and completeness. You must output JSON only."
    )
    system_content_text = f"{system_msg}\n\n**[Expert Registry]**\n{registry_summary}"
    system_message = {
        "role": "system",
        "content": [
            {
                "type": "text",
                "text": system_content_text,
                "cache_control": {"type": "ephemeral"},
            }
        ],
    }

    try:
        completion = api_call_with_retry(
            client.chat.completions.create,
            model=JUDGE_MODEL,
            messages=[
                system_message,
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{base64_image}"
                            },
                        },
                    ],
                },
            ],
            response_format={"type": "json_object"},
            temperature=temperature,
            max_retries=api_retry,
            label="Judge",
            extra_body={"enable_thinking": False},
        )
        cost_time = time.time() - start_time
        raw_content = completion.choices[0].message.content
        finish_reason = getattr(completion.choices[0], "finish_reason", "unknown")
        usage = getattr(completion, "usage", None)
        if raw_content is None or raw_content.strip() == "":
            reasoning = getattr(completion.choices[0].message, "reasoning_content", None)
            usage_info = f"prompt_tokens={usage.prompt_tokens}, completion_tokens={usage.completion_tokens}" if usage else "no usage info"
            print(f"  [ERROR] Judge returned empty content (content is {'None' if raw_content is None else 'empty string'}, finish_reason={finish_reason}, {usage_info})")
            if reasoning:
                print(f"  [WARN] Judge reasoning_content found ({len(reasoning)} chars), attempting to extract JSON")
                raw_content = reasoning
            else:
                msg = completion.choices[0].message
                print(f"  [DEBUG] Judge full message: content={repr(msg.content)}, role={getattr(msg, 'role', 'N/A')}, function_call={getattr(msg, 'function_call', None)}, tool_calls={getattr(msg, 'tool_calls', None)}, refusal={getattr(msg, 'refusal', None)}")
                return None
        result = parse_json_safely(raw_content)
        if result is None:
            print(f"  [ERROR] Judge returned unparseable JSON: {raw_content[:200]}")
            return None

        result["judge_cost_seconds"] = round(cost_time, 2)

        usage = getattr(completion, "usage", None)
        if usage:
            details = getattr(usage, "prompt_tokens_details", None)
            cached = getattr(details, "cached_tokens", 0) if details else 0
            created = getattr(details, "cache_creation_input_tokens", 0) if details else 0
            if cached or created:
                print(f"  [CACHE] Judge: hit={cached} tokens, created={created} tokens")

        return result
    except Exception as e:
        print(f"  [ERROR] Judge API call failed: {type(e).__name__}: {e}")
        return None
